### ISSUE TITLE
Kanged commits. 

### ISSUE THREAD

**Issue by USA-RedDragon** [SOKP/frameworks_base#2]
"What did you do to the comments? I don't believe you ported this all!!
Please correct the comment for this commit and: 61f7b7a.

The devs write comments for a reason. Have some repect for the devs that all worked on this code by
keeping the comments as it is written"

As quoted by NL-BlackDragon on
https://github.com/SOKP/frameworks_base/commit/89414b974a08b653d746802f13b2c86481d6f017
Also same applies to this commit, as well
https://github.com/SOKP/frameworks_base/commit/61f7b7a1d128b5353bbf983de75b50085a112706

**Comment by AudioGod** [comment]
I don't see any point on this issue .....since authorship is given from where i have picked it  and may be some comments of commit is missed ......if its a issues sorry for it .....in future all comments also will be included ..

cheers :+1:
